version: '3'

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  map-server:
    driver: local
  map-client:
    driver: local
  map-web:
    driver: local

services:

### map-server ##############################################
    map-server:
      build:
        context: ./map-server
      volumes:
        - ./log/map-server:/var/log
        - ./map-server/config:/usr/local/etc
      networks:
        - backend

### map-client ##############################################
    map-client:
      build:
        context: ./map-client
      volumes:
        - ./log/map-client:/var/log
        - ./map-client/config:/usr/local/etc
      #expose:
      #  - "9000"
      networks:
        - backend

### map-web ##############################################
    map-web:
      build:
        context: ./map-web
      volumes:
        - ../Web:/var/www/Web
        - ./log/map-web/php:/var/log/php
        # - ./map-web/nginx/conf.d /etc/nginx/conf.d
      ports:
        - "8080:8080"
        - "9502:9502"
      networks:
        - frontend
        - backend
      command: 
        - /bin/sh
        - -c
        # - nginx -g "daemon off;"
        - nginx && node /var/www/Web/Server/websocket.js
